### ISSUE TITLE
Extraction of syntax files.

### ISSUE THREAD

**Issue by majjoha** [sdiehl/haskell-vim-proto#3]
Is there any chance that the syntax files in this project could be extracted into its own repository?

It would be really convenient for people who wants maintained syntax files for Haskell, Cabal, and so forth without all the remaining parts of the repository.

**Comment by sdiehl** [comment]
I don't maintain the syntax files, should be easy enough to create a repo for yourself with just what you need though?

**Comment by majjoha** [comment]
Ah, I see. Sorry, I thought you were the maintainer of the syntax files, but I should've looked a bit closer at the actual files.
